### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by godslayer201**
Added a gif,to make it look interesting.

### CODE REVIEW

**Comment by ChoukseyKhushbu** [comment]
Yeah. The Organization(and the repository) has been made real quick in a span of a few hours.
Already thinking of adding emojis and gifs.
Though thanks for your PR. The gif is apt :smile: 
Will merge it soon.

**Comment by godslayer201** [comment]
sure. would it be alright if i add another PR for resources?

**Comment by ChoukseyKhushbu** [comment]
For resources, it will be better if you consider sending them in the slack first. If all the admins approve you can create a PR here too. Otherwise, there will be just too many unnecessary PRs here.

**Comment by godslayer201** [comment]
Sure. Thanks!

**Pull request merged**
