### PR TITLE
Adding Python solutions to problems of Mega Contest 1 (dated 16-08-2020)

### PR DESCRIPTION
**Pull request by Git-Harshit**
With this commit, Python solutions to four problems of Mega Contest 1, complete 3 solutions to problems: 1, 3, 4, and a partially correct (15/20 Testcases Passed) solution to problem 2, viz., Another Silly Mistake. 

Please look into the codes, and merge this pull request.

### CODE REVIEW

**Comment by adad20** [comment]
@Git-Harshit  The challenge which is partially correct can u remove it?

**Comment by Git-Harshit** [comment]
It was the solution to 2nd Problem, which was partially correct. Sure, I'll
remove it!

**Comment by Git-Harshit** [comment]
@adad20 Should be done! I've removed the partially correct solution to problem 2, Again Silly Mistake. Now, all the solutions provided are 100% correct. Please review again! 

Thanks!

**Comment by adad20** [comment]
@Git-Harshit Thanks for the PR!!

**Pull request merged**
