### PR TITLE
Another approach for solving 'Unique Number 3'

### PR DESCRIPTION
**Pull request by srikanth7785**
Using `map` Data Structure to solve it.

### CODE REVIEW

**Comment by adad20** [comment]
Thanks for this PR @srikanth7785. Can u make a seperate file for this approach like solution-1.cpp

**Comment by srikanth7785** [comment]
sure..on it..!

**Comment by srikanth7785** [comment]
now there are two files with each of them having a different approach

**Comment by adad20** [comment]
@srikanth7785 Thanks for your contributions. I am merging it.

**Pull request merged**
